# Generated by Django 2.2.5 on 2019-09-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_musica', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('link_musica', models.CharField(max_length=255)),
            ],
        ),
    ]
